
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alan S'
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    Conexao conecta = new Conexao();
    public Cadastro() {
        initComponents();
        conecta.conectar();
        //this.setExtendedState(this.getExtendedState()|Cadastro.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        tombamento = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        modelo = new javax.swing.JTextField();
        especificacao = new javax.swing.JComboBox();
        equipamentos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();
        salvar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        imgequip = new javax.swing.JLabel();
        imagem1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 80, 20);
        getContentPane().add(nome);
        nome.setBounds(20, 80, 250, 30);
        getContentPane().add(tombamento);
        tombamento.setBounds(20, 130, 250, 30);
        getContentPane().add(marca);
        marca.setBounds(20, 180, 250, 30);
        getContentPane().add(modelo);
        modelo.setBounds(20, 230, 250, 30);

        especificacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Óptico", "Mecânico", "Manual", "Digital", "Laser", "Outro" }));
        getContentPane().add(especificacao);
        especificacao.setBounds(20, 280, 250, 30);

        equipamentos.setText("Equipamento");
        equipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipamentosActionPerformed(evt);
            }
        });
        getContentPane().add(equipamentos);
        equipamentos.setBounds(360, 170, 120, 30);

        descricao.setColumns(20);
        descricao.setRows(5);
        jScrollPane1.setViewportView(descricao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 330, 250, 150);

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        getContentPane().add(salvar);
        salvar.setBounds(40, 500, 100, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lag.png"))); // NOI18N
        jLabel9.setText("jLabel3");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(620, 10, 180, 140);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Cadastro de Equipamentos");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 10, 284, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tombamento :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 120, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Marca :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 160, 80, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Modelo :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 210, 80, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Especificação :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 260, 110, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descrição :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 310, 90, 20);

        imgequip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        imgequip.setForeground(new java.awt.Color(255, 255, 255));
        imgequip.setText("IMG");
        getContentPane().add(imgequip);
        imgequip.setBounds(350, 60, 140, 100);

        imagem1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        imagem1.setForeground(new java.awt.Color(255, 255, 255));
        imagem1.setText("PDF");
        getContentPane().add(imagem1);
        imagem1.setBounds(570, 60, 180, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadastro.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 620);

        setSize(new java.awt.Dimension(815, 659));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void equipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipamentosActionPerformed
        JFileChooser fileChooser = new JFileChooser();    
        fileChooser.setDialogTitle("Imagem do Equipamento");    
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);    
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG  GIF & PNG Images", "jpg", "gif","png");  //Cria um filtro    
        fileChooser.setFileFilter(filter);  //Altera o filtro do JFileChooser  
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)    
        {      
            File img = fileChooser.getSelectedFile();
            String Imc = img.getPath();
            ImageIcon imagem = new ImageIcon(Imc); 
            Image img2 = imagem.getImage().getScaledInstance(140,100,Image.SCALE_DEFAULT);
            imgequip.setIcon(new ImageIcon(img2));
            
        }
    }//GEN-LAST:event_equipamentosActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        try {
            PreparedStatement pst = conecta.con.prepareStatement("INSERT into equipamentos (nome,tombamento, marca, modelo, especificacao, descricao) values (?,?,?,?,?,?)"); // Passagem do SQL
            pst.setString(1, nome.getText());
            pst.setString(2, tombamento.getText());
            pst.setString(3, marca.getText());
            pst.setString(4, modelo.getText());
            pst.setString(5, (String) especificacao.getSelectedItem());
            pst.setString(6, descricao.getText());// --
            pst.executeUpdate(); // Executar Inserção
            JOptionPane.showMessageDialog(null, "Equipamento Cadastrado com Sucesso!");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no Cadastro \n ERRO: !" + ex);
        }
        
    }//GEN-LAST:event_salvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descricao;
    private javax.swing.JButton equipamentos;
    private javax.swing.JComboBox especificacao;
    private javax.swing.JLabel imagem1;
    private javax.swing.JLabel imgequip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField nome;
    private javax.swing.JButton salvar;
    private javax.swing.JTextField tombamento;
    // End of variables declaration//GEN-END:variables
}
