
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alan S'
 */
public class Pesquisar extends javax.swing.JFrame {

    /**
     * Creates new form Pesquisar
     */
    Conexao conecta = new Conexao();
    public Pesquisar() {
        initComponents();
        conecta.conectar();
        preencherEquipamentos();
        ID.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nometomba = new javax.swing.JComboBox();
        pesquisar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        especificacao = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        tombamento = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        modelo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        excluir = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 40, 100, 30);

        getContentPane().add(nometomba);
        nometomba.setBounds(30, 70, 340, 30);

        pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisar);
        pesquisar.setBounds(380, 60, 130, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 120, 100, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descrição :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 420, 100, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tombamento :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 180, 100, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Marca :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 240, 100, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Modelo :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 300, 100, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Especificação");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 360, 100, 25);

        especificacao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(especificacao);
        especificacao.setBounds(30, 380, 250, 30);

        nome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(nome);
        nome.setBounds(30, 140, 250, 30);

        tombamento.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(tombamento);
        tombamento.setBounds(30, 200, 250, 30);

        marca.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(marca);
        marca.setBounds(30, 260, 250, 30);

        modelo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(modelo);
        modelo.setBounds(30, 320, 250, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lag.png"))); // NOI18N
        jLabel11.setText("jLabel3");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(580, 10, 180, 140);

        descricao.setColumns(20);
        descricao.setRows(5);
        descricao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(descricao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 440, 250, 100);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("IMG");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(340, 200, 130, 120);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Manual");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(540, 200, 130, 120);

        excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        getContentPane().add(excluir);
        excluir.setBounds(470, 490, 100, 40);

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/off.png"))); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair);
        sair.setBounds(650, 490, 100, 40);

        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        getContentPane().add(editar);
        editar.setBounds(360, 490, 100, 40);

        ID.setEditable(false);
        getContentPane().add(ID);
        ID.setBounds(320, 420, 80, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisa.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 760, 550);

        setSize(new java.awt.Dimension(771, 586));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
       conecta.executaSQL("select * from equipamentos where nome = '"+nometomba.getSelectedItem()+"' order by nome");
        try {
           conecta.rs.first();
            nome.setText(conecta.rs.getString("nome"));
            tombamento.setText(conecta.rs.getString("tombamento"));
            marca.setText(conecta.rs.getString("marca"));
            modelo.setText(conecta.rs.getString("modelo"));
            especificacao.setText(conecta.rs.getString("especificacao"));
            descricao.setText(conecta.rs.getString("descricao"));
            ID.setText(Integer.toString(conecta.rs.getInt("ID")));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao mostrar dados! \n ERRO: " + ex);
        }
        
    }//GEN-LAST:event_pesquisarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
       conecta.executaSQL("select * from equipamentos where id = '"+ID.getText()+"'");
        try {
            PreparedStatement pst = conecta.con.prepareStatement("UPDATE equipamentos set Nome = ?, Tombamento = ?, Marca = ?, Modelo = ?, Especificacao = ?, Descricao = ? where ID = ?");
            pst.setString(1, nome.getText());
            pst.setString(2, tombamento.getText());
            pst.setString(3, marca.getText());
            pst.setString(4, modelo.getText());
            pst.setString(5, especificacao.getText());
            pst.setString(6, descricao.getText());
            pst.setInt(7, Integer.parseInt(ID.getText()));
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Equipamento Editado com Sucesso!");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Alterar \n ERRO: !" + ex);
        }
        nometomba.removeAllItems(); 
        preencherEquipamentos();
    }//GEN-LAST:event_editarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        conecta.executaSQL("select * from equipamentos where id = '"+ID.getText()+"'");
        try {
            PreparedStatement pst = conecta.con.prepareStatement("DELETE FROM equipamentos WHERE id = ?");
            pst.setString(1, ID.getText());
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Equipamento Excluido com Sucesso!");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro na Exclusão \n ERRO: !" + ex);
        }
        nometomba.removeAllItems();
        preencherEquipamentos();
    }//GEN-LAST:event_excluirActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void preencherEquipamentos() {
        conecta.conectar();
        conecta.executaSQL("select * from equipamentos order by nome");
        try {
            conecta.rs.first();
            do {
                nometomba.addItem(conecta.rs.getString("nome"));
            } while (conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no combobox \n ERRO: " + ex);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesquisar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JTextArea descricao;
    private javax.swing.JButton editar;
    private javax.swing.JTextField especificacao;
    private javax.swing.JButton excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField nome;
    private javax.swing.JComboBox nometomba;
    private javax.swing.JButton pesquisar;
    private javax.swing.JButton sair;
    private javax.swing.JTextField tombamento;
    // End of variables declaration//GEN-END:variables
}
